import { Product } from './types';

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'seed-1',
    name: 'Camiseta Eco Basica',
    description: 'Camiseta basica produzida com algodao 100% organico certificado. Tingimento natural sem quimicos.',
    image: '/products/tshirt.jpg',
    size: 'M',
    quantity: 25,
    price: 89.90,
    supplier: 'EcoTextil Brasil',
    supplierCity: 'Sao Paulo',
    isLocal: true,
    material: 'algodao-organico',
    sustainabilityScore: 9,
    carbonFootprint: 2.1,
    category: 'Camiseta',
  },
  {
    id: 'seed-2',
    name: 'Calca Jeans Reciclada',
    description: 'Calca jeans produzida com denim reciclado. Processo de lavagem com economia de 80% de agua.',
    image: '/products/jeans.jpg',
    size: 'G',
    quantity: 15,
    price: 159.90,
    supplier: 'Jeans Circular',
    supplierCity: 'Belo Horizonte',
    isLocal: false,
    material: 'poliester-reciclado',
    sustainabilityScore: 8,
    carbonFootprint: 3.5,
    category: 'Calca',
  },
  {
    id: 'seed-3',
    name: 'Vestido de Linho Natural',
    description: 'Vestido elegante confeccionado em linho puro. Fibra natural biodegradavel e hipoalergenica.',
    image: '/products/dress.jpg',
    size: 'P',
    quantity: 10,
    price: 219.90,
    supplier: 'Linho & Arte',
    supplierCity: 'Sao Paulo',
    isLocal: true,
    material: 'linho',
    sustainabilityScore: 9,
    carbonFootprint: 1.8,
    category: 'Vestido',
  },
  {
    id: 'seed-4',
    name: 'Moletom de Bambu',
    description: 'Moletom aconchegante feito com fibra de bambu. Antibacteriano natural e termorregulador.',
    image: '/products/hoodie.jpg',
    size: 'G',
    quantity: 20,
    price: 179.90,
    supplier: 'BambuWear',
    supplierCity: 'Curitiba',
    isLocal: false,
    material: 'bambu',
    sustainabilityScore: 8,
    carbonFootprint: 2.0,
    category: 'Moletom',
  },
  {
    id: 'seed-5',
    name: 'Polo Organica Premium',
    description: 'Polo classica em algodao organico premium. Botoes de coco reciclado.',
    image: '/products/polo.jpg',
    size: 'M',
    quantity: 18,
    price: 129.90,
    supplier: 'EcoTextil Brasil',
    supplierCity: 'Sao Paulo',
    isLocal: true,
    material: 'algodao-organico',
    sustainabilityScore: 9,
    carbonFootprint: 2.1,
    category: 'Polo',
  },
  {
    id: 'seed-6',
    name: 'Jaqueta PET Reciclada',
    description: 'Jaqueta feita com poliester 100% reciclado de garrafas PET. Cada peca reutiliza 12 garrafas.',
    image: '/products/jacket.jpg',
    size: 'G',
    quantity: 8,
    price: 249.90,
    supplier: 'ReciclaFashion',
    supplierCity: 'Porto Alegre',
    isLocal: false,
    material: 'poliester-reciclado',
    sustainabilityScore: 8,
    carbonFootprint: 3.5,
    category: 'Jaqueta',
  },
  {
    id: 'seed-7',
    name: 'Calca Casual de Canhamo',
    description: 'Calca casual confeccionada em canhamo organico. Uma das fibras mais sustentaveis do mundo.',
    image: '/products/pants.jpg',
    size: 'M',
    quantity: 12,
    price: 199.90,
    supplier: 'Hemp Brasil',
    supplierCity: 'Florianopolis',
    isLocal: false,
    material: 'canhamo',
    sustainabilityScore: 10,
    carbonFootprint: 1.5,
    category: 'Calca',
  },
  {
    id: 'seed-8',
    name: 'Blusa Tencel Elegante',
    description: 'Blusa sofisticada em Tencel/Lyocell. Fibra produzida a partir de celulose de madeira reflorestada.',
    image: '/products/blouse.jpg',
    size: 'P',
    quantity: 14,
    price: 149.90,
    supplier: 'Linho & Arte',
    supplierCity: 'Sao Paulo',
    isLocal: true,
    material: 'tencel',
    sustainabilityScore: 8,
    carbonFootprint: 2.3,
    category: 'Blusa',
  },
];
